language: node_js

node_js: 
  - "stable"

cache: yarn

before_install:
  # set up awscli packages
  - pip install --user awscli

install:
  - yarn install

before_script:
  - cd ./dataSrc
  - npm install
  - rm dangerousCarList.xlsx
  - wget -O dangerousCarList.xlsx https://docs.google.com/spreadsheets/d/$SHEET_ID/export?format=xlsx
  - node exportData
  - cd ../

script:
  - yarn build

after_success:
  - aws s3 cp ./build/ s3://$S3_BUCKET/ --recursive
  - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_ID" --paths "/*"