language: node_js

node_js: 
  - "stable"

cache: yarn

before_install:
  # set up awscli packages
  - pip install --user awscli
  # set up yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

before_script:
  - cd ./dataSrc
  - npm install
  - rm dangerousCarList.xlsx
  - wget -O dangerousCarList.xlsx https://docs.google.com/spreadsheets/d/$SHEET_ID/export?format=xlsx
  - node exportData

script:
  - yarn build

deploy:
  - aws s3 cp ./build/ s3://$S3_BUCKET/ --recursive
  - aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_ID" --paths "/*"